name = realistic_fluids
description = Physics Mod for Luanti: Gerstner ocean waves with buoyancy, and building debris with falling fragments.
depends = default
optional_depends = flowers, climate_api, regional_weather
